[package]
name = "splash"
version = "0.1.0"
authors = ["Stuart Reilly <stu@reilly-family.co.uk>"]

[workspace]

[dependencies]
splash-rs = {version = "*", path="lib/"}
hyper-rustls = "0.14"
hyper = "0.12"
